language: rust
rust:
  - 1.40.0
  - stable
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      script: cargo test -Z minimal-versions --all-features

script:
  - cargo test
  - cargo test --features "diagnostics"
  - cargo test --features "diagnostics,tynm"

