language: rust
rust:
  - 1.40.0
  - stable
  - nightly

jobs:
  allow_failures:
    - rust: nightly

script:
  - cargo test
  - cargo test --features "diagnostics"
  - cargo test --features "diagnostics,tynm"
  - cargo +nightly test --features "unsized"
  - cargo +nightly test --features "unsized,diagnostics"
  - cargo +nightly test --features "unsized,diagnostics,tynm"

