[package]
name = "daab"
version = "0.3.0"
authors = ["cryptjar <cryptjar@junk.studio>", "dezajno <dezajno@junk.studio>"]
edition = "2018"
description = "DAG aware artifact builder"

repository = "https://github.com/CoffeJunkStudio/daab"
readme = "README.md"
#license = "Apache-2.0"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
diagnostics = []

[dependencies]


[dev-dependencies]
regex = "1.3"


