[package]
name = "daab"
version = "0.1.0"
authors = ["cryptjar <cryptjar@junk.studio>", "dezajno <marvinlunz@gmail.com>"]
edition = "2018"
description = "DAG aware artifact builder"

repository = "https://github.com/dezajno/daab"
readme = "README.md"
license = "Apache-2.0"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

