name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Env
      run: |
        cargo --version
        rustc --version
    - name: Build
      run: |
        cargo build --verbose
        cargo build --all-features --verbose
    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --features diagnostics --verbose
        cargo test --all-features --verbose
